server:
  port: 8010

spring:
  application:
    name: payment-service

  iamport:
    api:
      key: ${IAMPORT_API_KEY}
      secret: ${IAMPORT_API_SECRET} # ???? API Secret Key

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10000/eureka
