eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10000/eureka

server:
  port: 8007

spring:
  application:
    name: project-service
      