version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-project-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: projectDB
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - project-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 개발 환경에서는 보안 비활성화
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - project-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - project-network

volumes:
  mysql-data:
  esdata:

networks:
  project-network:
