version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-project-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: projectDB
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./logs:/app/logs
    networks:
      - project-network
      - logging-net

  filebeat:
    build: ./filebeat
    container_name: filebeat
    user: root
    volumes:
      - ./logs:/app/logs:ro
    depends_on:
      - mysql
      - logstash
    networks:
      - logging-net

volumes:
  mysql-data:
  esdata:

networks:
  project-network:
  logging-net:
    external: true
