version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth-db
    ports:
      - "3008:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: authDB
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mysql-data:
  redis-data: