server:
  port: 9000

spring:
  main:
    web-application-type: reactive

  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:10000/eureka
