version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-order-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: orderDB
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
